version: '2'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    # network_mode: host
    hostname: 'zookeeper'
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    # extra_hosts:
    # - "moby:127.0.0.1"

  kafka:
    image: confluentinc/cp-kafka:latest
    # network_mode: host
    hostname: 'kafka'
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:9092'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    # extra_hosts:
    #   - "moby:127.0.0.1"

  kafka-manager:
    image: hlebalbau/kafka-manager:latest
    hostname: 'kafka-manager'
    ports:
      - "9000:9000"
    depends_on:
      - zookeeper
      - kafka
    environment:
      ZK_HOSTS: 'zookeeper:2181'
      APPLICATION_SECRET: 'letmein'
    command: -Dpidfile.path=/dev/null
