version: '2'
services:
  zookeeper1:
    image: zookeeper:latest
    # restart: always
    ports:
      - "12181:2181"
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zookeeper1:2888:3888 server.2=zookeeper2:2888:3888

  zookeeper2:
    image: zookeeper:latest
    # restart: always
    ports:
      - "22181:2181"
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zookeeper1:2888:3888 server.2=zookeeper2:2888:3888

  kafka1:
    image: wurstmeister/kafka:latest
    ports:
      - "19092:9092"
    depends_on:
      - zookeeper1
      - zookeeper2
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper1:2181,zookeeper2:2182'
      # KAFKA_ZOOKEEPER_CONNECT: localhost:22181,localhost:32181,localhost:42181
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka1:9092'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      # KAFKA_ADVERTISED_HOST_NAME: localhost

  kafka2:
    image: wurstmeister/kafka:latest
    ports:
      - "29092:9092"
    depends_on:
      - zookeeper1
      - zookeeper2
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper1:2181,zookeeper2:2182'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka2:9092'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafka-manager:
    image: hlebalbau/kafka-manager:latest
    ports:
      - "9000:9000"
    depends_on:
      - zookeeper1
      - zookeeper2
      - kafka1
      - kafka2
    environment:
      ZK_HOSTS: 'zookeeper1:2181'
      APPLICATION_SECRET: 'letmein'
    command: -Dpidfile.path=/dev/null
