web:
  image: 'gitlab/gitlab-ce:latest'
  restart: always
  hostname: 'git.f88.dev'
  environment:
    GITLAB_OMNIBUS_CONFIG: |
      external_url 'http://git.f88.dev:9000'
      nginx['listen_port'] = 80
      # Add any other gitlab.rb configuration here, each on its own line
      gitlab_rails['gitlab_shell_ssh_port'] = 9022
      unicorn['worker_processes'] = 2
      # Email
      #gitlab_rails['smtp_enable'] = true
      #gitlab_rails['smtp_address'] = "smtp.mailgun.org"
      #gitlab_rails['smtp_port'] = 587
      #gitlab_rails['smtp_authentication'] = "plain"
      #gitlab_rails['smtp_enable_starttls_auto'] = true
      #gitlab_rails['smtp_user_name'] = "postmaster@sandboxc7a2619b17bc413f94dc68c0c59c8468.mailgun.org"
      #gitlab_rails['smtp_password'] = "b3b8dbad8b89e0b7fb7bcb7a720e9151"
      #gitlab_rails['smtp_domain'] = "sandboxc7a2619b17bc413f94dc68c0c59c8468.mailgun.org"
  ports:
    - '9000:80'
    - '9443:443'
    - '9022:22'
  volumes:
    - '/srv/gitlab/config:/etc/gitlab'
    - '/srv/gitlab/logs:/var/log/gitlab'
    - '/srv/gitlab/data:/var/opt/gitlab'
